[package]
name = "decompression-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "2.1.1"
log = "0.4.21"
clap = "4.5.4"
